server:
  name: "project-api"
  addr: "127.0.0.1:8888"
zap:
  debugFileName: "/home/fjw/GolandProjects/my_project/logs/debug/project-debug.log"
  infoFileName: "/home/fjw/GolandProjects/my_project/logs/info/project-info.log"
  warnFileName: "/home/fjw/GolandProjects/my_project/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"