server:
  name: "project-project"
  addr: "127.0.0.1:8081"
zap:
  debugFileName: "/home/fjw/GolandProjects/my_project/logs/debug/project-debug.log"
  infoFileName: "/home/fjw/GolandProjects/my_project/logs/info/project-info.log"
  warnFileName: "/home/fjw/GolandProjects/my_project/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "project"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"

mysql:
  username: root
  password: Fjw20030504
  host: 127.0.0.1
  port: 3306
  db: ms_project
db:
  separation: true
  master:
    name: master
    username: root
    password: Fjw20030504
    host: 127.0.0.1
    port: 3306
    db: ms_project
  slave:
    - username: root
      password: Fjw20030504
      host: 127.0.0.1
      port: 3306
      db: ms_project
      name: slave1
    - username: root
      password: Fjw20030504
      host: 127.0.0.1
      port: 3306
      db: ms_project
      name: slave2
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project